---
abstract: 'Code server side, use client side.'
author:
  - 'Eric Wolf (coyocanid@gmail.com)'
build_requires:
  Test::More: 0
  Test::Pod: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Yote
provides:
  Yote:
    file: lib/Yote.pm
    version: 0.1010
  Yote::Account:
    file: lib/Yote/Account.pm
    version: 0.05
  Yote::AppRoot:
    file: lib/Yote/AppRoot.pm
    version: 0.087
  Yote::Array:
    file: lib/Yote/Array.pm
    version: 0.02
  Yote::Cron:
    file: lib/Yote/Cron.pm
    version: 0.014
  Yote::FileHelper:
    file: lib/Yote/FileHelper.pm
    version: 0.012
  Yote::Hash:
    file: lib/Yote/Hash.pm
    version: 0.02
  Yote::IO::Mongo:
    file: lib/Yote/IO/Mongo.pm
    version: 0.037
  Yote::IO::Mysql:
    file: lib/Yote/IO/Mysql.pm
    version: 0.034
  Yote::IO::SQLite:
    file: lib/Yote/IO/SQLite.pm
    version: 0.035
  Yote::IO::TestUtil:
    file: lib/Yote/IO/TestUtil.pm
    version: 0.001
  Yote::Login:
    file: lib/Yote/Login.pm
    version: 0.04
  Yote::Obj:
    file: lib/Yote/Obj.pm
    version: 0.072
  Yote::ObjManager:
    file: lib/Yote/ObjManager.pm
    version: 0.02
  Yote::ObjProvider:
    file: lib/Yote/ObjProvider.pm
    version: 0.072
  Yote::PerfAspect:
    file: lib/Yote/PerfAspect.pm
    version: 0.01
  Yote::RootObj:
    file: lib/Yote/RootObj.pm
  Yote::Sample::SecretCollect:
    file: lib/Yote/Sample/SecretCollect.pm
    version: 0.01
  Yote::Sample::SimpleTodo:
    file: lib/Yote/Sample/SimpleToDo.pm
    version: 0.02
  Yote::Test::Hello:
    file: lib/Yote/Test/Hello.pm
    version: 0.02
  Yote::Test::TestAppNeedsLogin:
    file: lib/Yote/Test/TestAppNeedsLogin.pm
    version: 0.02
  Yote::Test::TestAppNoLogin:
    file: lib/Yote/Test/TestAppNoLogin.pm
    version: 0.02
  Yote::Test::TestDeepCloner:
    file: lib/Yote/Test/TestDeepCloner.pm
    version: 0.01
  Yote::Test::TestNoDeepCloner:
    file: lib/Yote/Test/TestNoDeepCloner.pm
    version: 0.01
  Yote::UserObj:
    file: lib/Yote/UserObj.pm
  Yote::WebAppServer:
    file: lib/Yote/WebAppServer.pm
    version: 0.098
  Yote::YoteRoot:
    file: lib/Yote/YoteRoot.pm
    version: 0.052
requires:
  Aspect: 1.04
  Crypt::Passwd::XS: 0.601
  DBD::SQLite: 1.35
  DBI: 1.625
  DateTime: 0.77
  Email::Valid: 0.19
  File::UStore: 0.12
  JSON: 2.53
  MIME::Base64: 0
  Mail::Sender: 0
  Test::More: 0
  Test::Pod: 0
  WeakRef: 0.01
  forks: 0.34
  forks::shared: 0.34
  perl: v5.12.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.1010
