---
abstract: 'Code server side, use client side.'
author:
  - 'Eric Wolf (coyocanid@gmail.com)'
build_requires:
  Test::More: 0
  Test::Pod: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Yote
provides:
  Yote:
    file: lib/Yote.pm
    version: 0.1005
  Yote::Account:
    file: lib/Yote/Account.pm
    version: 0.03
  Yote::AppRoot:
    file: lib/Yote/AppRoot.pm
    version: 0.087
  Yote::Array:
    file: lib/Yote/Array.pm
    version: 0.01
  Yote::Cache:
    file: lib/Yote/Cache.pm
    version: 0.01
  Yote::Cron:
    file: lib/Yote/Cron.pm
    version: 0.011
  Yote::DummyCache:
    file: lib/Yote/DummyCache.pm
    version: 0.01
  Yote::FileHelper:
    file: lib/Yote/FileHelper.pm
    version: 0.012
  Yote::Hash:
    file: lib/Yote/Hash.pm
    version: 0.01
  Yote::Login:
    file: lib/Yote/Login.pm
    version: 0.02
  Yote::Messenger:
    file: lib/Yote/Messenger.pm
    version: 0.01
  Yote::MongoIO:
    file: lib/Yote/MongoIO.pm
    version: 0.032
  Yote::MysqlIO:
    file: lib/Yote/MysqlIO.pm
    version: 0.032
  Yote::Obj:
    file: lib/Yote/Obj.pm
    version: 0.07
  Yote::ObjManager:
    file: lib/Yote/ObjManager.pm
    version: 0.01
  Yote::ObjProvider:
    file: lib/Yote/ObjProvider.pm
    version: 0.07
  Yote::SQLiteIO:
    file: lib/Yote/SQLiteIO.pm
    version: 0.031
  Yote::Sample::SecretCollect:
    file: lib/Yote/Sample/SecretCollect.pm
    version: 0.01
  Yote::Sample::SimpleTodo:
    file: lib/Yote/Sample/SimpleToDo.pm
    version: 0.02
  Yote::SimpleLRUCache:
    file: lib/Yote/SimpleLRUCache.pm
    version: 0.02
  Yote::Test::Hello:
    file: lib/Yote/Test/Hello.pm
    version: 0.02
  Yote::Test::TestAppNeedsLogin:
    file: lib/Yote/Test/TestAppNeedsLogin.pm
    version: 0.02
  Yote::Test::TestAppNoLogin:
    file: lib/Yote/Test/TestAppNoLogin.pm
    version: 0.02
  Yote::Test::TestDeepCloner:
    file: lib/Yote/Test/TestDeepCloner.pm
    version: 0.01
  Yote::Test::TestNoDeepCloner:
    file: lib/Yote/Test/TestNoDeepCloner.pm
    version: 0.01
  Yote::Util::Admin:
    file: lib/Yote/Util/Admin.pm
    version: 0.01
  Yote::Util::Blog:
    file: lib/Yote/Util/Blog.pm
    version: 0.02
  Yote::Util::BlogPost:
    file: lib/Yote/Util/BlogPost.pm
    version: 0.02
  Yote::Util::CMS:
    file: lib/Yote/Util/CMS.pm
    version: 0.02
  Yote::Util::ChatBoard:
    file: lib/Yote/Util/ChatBoard.pm
    version: 0.01
  Yote::Util::Counter:
    file: lib/Yote/Util/Counter.pm
    version: 0.01
  Yote::Util::MadYote:
    file: lib/Yote/Util/MadYote.pm
    version: 0.021
  Yote::Util::MessageBoard:
    file: lib/Yote/Util/MessageBoard.pm
    version: 0.01
  Yote::Util::Tag:
    file: lib/Yote/Util/Tag.pm
    version: 0.01
  Yote::Util::Wiki:
    file: lib/Yote/Util/Wiki.pm
    version: 0.01
  Yote::WebAppServer:
    file: lib/Yote/WebAppServer.pm
    version: 0.095
  Yote::YoteRoot:
    file: lib/Yote/YoteRoot.pm
    version: 0.051
requires:
  Crypt::Passwd::XS: 0.601
  DBD::SQLite: 1.35
  DBI: 1.625
  DateTime: 0.77
  Email::Valid: 0.19
  File::UStore: 0.12
  JSON: 2.53
  MIME::Base64: 0
  Mail::Sender: 0
  MongoDB: 0.503
  Test::More: 0
  Test::Pod: 0
  WeakRef: 0.01
  forks: 0.34
  forks::shared: 0.34
  perl: v5.12.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.1005
