---
abstract: 'Code server side, use client side.'
author:
  - 'Eric Wolf (coyocanid@gmail.com)'
build_requires:
  Test::More: '0'
  Test::Pod: '0'
configure_requires:
  Module::Build: '0.40'
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Yote
provides:
  Yote:
    file: lib/Yote.pm
    version: '0.225'
  Yote::Account:
    file: lib/Yote/Account.pm
    version: '0.05'
  Yote::AppRoot:
    file: lib/Yote/AppRoot.pm
    version: '0.089'
  Yote::Array:
    file: lib/Yote/Array.pm
    version: '0.02'
  Yote::Cron:
    file: lib/Yote/Cron.pm
    version: '0.015'
  Yote::Engine:
    file: lib/Yote/Engine.pm
    version: '0.002'
  Yote::FileHelper:
    file: lib/Yote/FileHelper.pm
    version: '0.012'
  Yote::Hash:
    file: lib/Yote/Hash.pm
    version: '0.02'
  Yote::IO::Mailer:
    file: lib/Yote/IO/Mailer.pm
  Yote::IO::Mongo:
    file: lib/Yote/IO/Mongo.pm
    version: '0.038'
  Yote::IO::Mysql:
    file: lib/Yote/IO/Mysql.pm
    version: '0.035'
  Yote::IO::SMTP:
    file: lib/Yote/IO/SMTP.pm
  Yote::IO::SQLite:
    file: lib/Yote/IO/SQLite.pm
    version: '0.036'
  Yote::IO::TestUtil:
    file: lib/Yote/IO/TestUtil.pm
    version: '0.001'
  Yote::Login:
    file: lib/Yote/Login.pm
    version: '0.04'
  Yote::Obj:
    file: lib/Yote/Obj.pm
    version: '0.074'
  Yote::ObjManager:
    file: lib/Yote/ObjManager.pm
    version: '0.02'
  Yote::ObjProvider:
    file: lib/Yote/ObjProvider.pm
    version: '0.073'
  Yote::Page:
    file: lib/Yote/Page.pm
  Yote::PerfAspect:
    file: lib/Yote/PerfAspect.pm
    version: '0.01'
  Yote::Root:
    file: lib/Yote/Root.pm
    version: '0.053'
  Yote::RootObj:
    file: lib/Yote/RootObj.pm
  Yote::SimpleTemplate:
    file: lib/Yote/SimpleTemplate.pm
  Yote::Test::Hello:
    file: lib/Yote/Test/Hello.pm
    version: '0.02'
  Yote::Test::Template:
    file: lib/Yote/Test/Template.pm
    version: '0.02'
  Yote::Test::TestAppNeedsLogin:
    file: lib/Yote/Test/TestAppNeedsLogin.pm
    version: '0.02'
  Yote::Test::TestAppNoLogin:
    file: lib/Yote/Test/TestAppNoLogin.pm
    version: '0.02'
  Yote::Test::TestDeepCloner:
    file: lib/Yote/Test/TestDeepCloner.pm
    version: '0.01'
  Yote::Test::TestNoDeepCloner:
    file: lib/Yote/Test/TestNoDeepCloner.pm
    version: '0.01'
  Yote::UserObj:
    file: lib/Yote/UserObj.pm
  Yote::Util::Pages:
    file: lib/Yote/Util/Pages.pm
  Yote::WebAppServer:
    file: lib/Yote/WebAppServer.pm
    version: '0.24'
recommends:
  Authen::NTLM: '1'
  DBD::mysql: '4.025'
  Digest::HMAC_MD5: '1'
  MongoDB: '0'
requires:
  Aspect: '1.04'
  Crypt::Passwd::XS: '0.601'
  DBD::SQLite: '1.35'
  DBI: '1.625'
  Daemon::Daemonize: '0.0052'
  DateTime: '0.77'
  Email::Valid: '0.19'
  File::Path: '2.09'
  File::Slurp: '9999.19'
  File::Temp: '0.23'
  File::UStore: '0.14'
  File::stat: '0.07'
  IO::Handle: '1.34'
  JSON: '2.53'
  JavaScript::Minifier: '1.11'
  MIME::Base64: '0'
  Mail::Sender: '0'
  POSIX: '1.32'
  Test::More: '0'
  Test::Pod: '0'
  Time::HiRes: '1.9725'
  WeakRef: '0.01'
  perl: v5.12.0
resources:
  license: http://dev.perl.org/licenses/
version: '0.225'
